### ISSUE TITLE
[Bug Report] Cannot find `train_batch_size` in `LanguageModelSAERunnerConfig.__init__()`

### ISSUE THREAD

**Issue by MClarke1991** [jbloomAus/SAELens#161]
### Bug

When trying to run "tutorials/training_a_sparse_autoencoder.ipynb" in a Google Colab notebook with SAElens python package installed, I get the error 

```
TypeError                                 Traceback (most recent call last)

/tmp/ipykernel_2837/4019108468.py in <cell line: 1>()
----> 1 cfg = LanguageModelSAERunnerConfig(
      2     # Data Generating Function (Model + Training Distibuion)
      3     model_name="tiny-stories-1L-21M",  # our model (more options here: https://neelnanda-io.github.io/TransformerLens/generated/model_properties_table.html)
      4     hook_point="blocks.0.hook_mlp_out",  # A valid hook point (see more details here: https://neelnanda-io.github.io/TransformerLens/generated/demos/Main_Demo.html#Hook-Points)
      5     hook_point_layer=0,  # Only one layer in the model.

TypeError: LanguageModelSAERunnerConfig.__init__() got an unexpected keyword argument 'train_batch_size'
```

### Code example

```
cfg = LanguageModelSAERunnerConfig(
    # Data Generating Function (Model + Training Distibuion)
    model_name="tiny-stories-1L-21M",  # our model (more options here: https://neelnanda-io.github.io/TransformerLens/generated/model_properties_table.html)
    hook_point="blocks.0.hook_mlp_out",  # A valid hook point (see more details here: https://neelnanda-io.github.io/TransformerLens/generated/demos/Main_Demo.html#Hook-Points)
    hook_point_layer=0,  # Only one layer in the model.
    d_in=1024,  # the width of the mlp output.
    dataset_path="apollo-research/roneneldan-TinyStories-tokenizer-gpt2",  # this is a tokenized language dataset on Huggingface for the Tiny Stories corpus.
    is_dataset_tokenized=True,
    streaming=True,  # we could pre-download the token dataset if it was small.
    # SAE Parameters
    mse_loss_normalization=None,  # We won't normalize the mse loss,
    expansion_factor=16,  # the width of the SAE. Larger will result in better stats but slower training.
    b_dec_init_method="zeros",  # The geometric median can be used to initialize the decoder weights.
    apply_b_dec_to_input=False,  # We won't apply the decoder weights to the input.
    normalize_sae_decoder=False,
    scale_sparsity_penalty_by_decoder_norm=True,
    decoder_heuristic_init=True,
    init_encoder_as_decoder_transpose=True,
    normalize_activations=True,
    # Training Parameters
    lr=5e-5,  # lower the better, we'll go fairly high to speed up the tutorial.
    adam_beta1=0.9,  # adam params (default, but once upon a time we experimented with these.)
    adam_beta2=0.999,
    lr_scheduler_name="constant",  # constant learning rate with warmup. Could be better schedules out there.
    lr_warm_up_steps=lr_warm_up_steps,  # this can help avoid too many dead features initially.
    lr_decay_steps=lr_decay_steps,  # this will help us avoid overfitting.
    l1_coefficient=5,  # will control how sparse the feature activations are
    l1_warm_up_steps=l1_warm_up_steps,  # this can help avoid too many dead features initially.
    lp_norm=1.0,  # the L1 penalty (and not a Lp for p < 1)
    train_batch_size_tokens=batch_size,
    context_size=256,  # will control the lenght of the prompts we feed to the model. Larger is better but slower. so for the tutorial we'll use a short one.
    # Activation Store Parameters
    n_batches_in_buffer=64,  # controls how many activations we store / shuffle.
    training_tokens=total_training_tokens,  # 100 million tokens is quite a few, but we want to see good stats. Get a coffee, come back.
    store_batch_size_prompts=16,
    # Resampling protocol
    use_ghost_grads=False,  # we don't use ghost grads anymore.
    feature_sampling_window=1000,  # this controls our reporting of feature sparsity stats
    dead_feature_window=1000,  # would effect resampling or ghost grads if we were using it.
    dead_feature_threshold=1e-4,  # would effect resampling or ghost grads if we were using it.
    # WANDB
    log_to_wandb=True,  # always use wandb unless you are just testing code.
    wandb_project="sae_lens_tutorial",
    wandb_log_frequency=30,
    eval_every_n_wandb_logs=20,
    # Misc
    device=device,
    seed=42,
    n_checkpoints=0,
    checkpoint_path="checkpoints",
    dtype=torch.float32,
)
```

### System info

Google Colab notebook

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/jbloomAus/SAELens/issues) in the repo (**required**)

**Comment by 4gatepylon** [comment]
@MClarke1991 I think you can fix it if you replace the key `train_batch_size` with `train_batch_size_tokens`. You might need to change the `dtype` parameter to be just the string `"float32"`. AFAIK this is a documentation issue.

**Comment by 4gatepylon** [comment]
# Description
Also, in case anyone reads this, I keep getting this issue that is really annoying to track down. When I switch from hook point `hook_mlp_out` to `attn.hook_z`after a fixed number of training epochs (or whatever you'd call these; for me its 9 with batch size 128 as you'll see below). It fails with the error (first error, then config on the bottom as a JSON which is passed as kwargs)

**Has anyone run into this error and found a fix? What is going on?**

# Error
```
Traceback (most recent call last):
  File "/home/ubuntu/git/IfYouDontUnderstandItDontUseIt/src/saes.py", line 184, in train_saes
    sparse_autoencoder: TrainingSAE = sae_training_runner.run()
  File "/home/ubuntu/git/IfYouDontUnderstandItDontUseIt/src/.venv/lib/python3.10/site-packages/sae_lens/sae_training_runner.py", line 81, in run
    sae = self.run_trainer_with_interruption_handling(trainer)
  File "/home/ubuntu/git/IfYouDontUnderstandItDontUseIt/src/.venv/lib/python3.10/site-packages/sae_lens/sae_training_runner.py", line 124, in run_trainer_with_interruption_handling
    sae = trainer.fit()
  File "/home/ubuntu/git/IfYouDontUnderstandItDontUseIt/src/.venv/lib/python3.10/site-packages/sae_lens/training/sae_trainer.py", line 172, in fit
    self._run_and_log_evals()
  File "/home/ubuntu/git/IfYouDontUnderstandItDontUseIt/src/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/git/IfYouDontUnderstandItDontUseIt/src/.venv/lib/python3.10/site-packages/sae_lens/training/sae_trainer.py", line 321, in _run_and_log_evals
    eval_metrics = run_evals(
  File "/home/ubuntu/git/IfYouDontUnderstandItDontUseIt/src/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/git/IfYouDontUnderstandItDontUseIt/src/.venv/lib/python3.10/site-packages/sae_lens/evals.py", line 28, in run_evals
    losses_df = recons_loss_batched(
  File "/home/ubuntu/git/IfYouDontUnderstandItDontUseIt/src/.venv/lib/python3.10/site-packages/sae_lens/evals.py", line 98, in recons_loss_batched
    score, loss, recons_loss, zero_abl_loss = get_recons_loss(
  File "/home/ubuntu/git/IfYouDontUnderstandItDontUseIt/src/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/git/IfYouDontUnderstandItDontUseIt/src/.venv/lib/python3.10/site-packages/sae_lens/evals.py", line 196, in get_recons_loss
    recons_loss = model.run_with_hooks(
  File "/home/ubuntu/git/IfYouDontUnderstandItDontUseIt/src/.venv/lib/python3.10/site-packages/transformer_lens/hook_points.py", line 358, in run_with_hooks
    return hooked_model.forward(*model_args, **model_kwargs)
  File "/home/ubuntu/git/IfYouDontUnderstandItDontUseIt/src/.venv/lib/python3.10/site-packages/transformer_lens/HookedTransformer.py", line 550, in forward
    residual = block(
  File "/home/ubuntu/git/IfYouDontUnderstandItDontUseIt/src/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/git/IfYouDontUnderstandItDontUseIt/src/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/git/IfYouDontUnderstandItDontUseIt/src/.venv/lib/python3.10/site-packages/transformer_lens/components.py", line 1585, in forward
    self.attn(
  File "/home/ubuntu/git/IfYouDontUnderstandItDontUseIt/src/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/git/IfYouDontUnderstandItDontUseIt/src/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/git/IfYouDontUnderstandItDontUseIt/src/.venv/lib/python3.10/site-packages/transformer_lens/components.py", line 587, in forward
    z = self.calculate_z_scores(v, pattern)  # [batch, pos, head_index, d_head]
  File "/home/ubuntu/git/IfYouDontUnderstandItDontUseIt/src/.venv/lib/python3.10/site-packages/transformer_lens/components.py", line 764, in calculate_z_scores
    z = self.hook_z(
  File "/home/ubuntu/git/IfYouDontUnderstandItDontUseIt/src/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/git/IfYouDontUnderstandItDontUseIt/src/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1595, in _call_impl
    hook_result = hook(self, args, result)
  File "/home/ubuntu/git/IfYouDontUnderstandItDontUseIt/src/.venv/lib/python3.10/site-packages/transformer_lens/hook_points.py", line 77, in full_hook
    return hook(module_output, hook=self)
  File "/home/ubuntu/git/IfYouDontUnderstandItDontUseIt/src/.venv/lib/python3.10/site-packages/sae_lens/evals.py", line 140, in standard_replacement_hook
    activations = sae.decode(sae.encode(activations)).to(activations.dtype)
  File "/home/ubuntu/git/IfYouDontUnderstandItDontUseIt/src/.venv/lib/python3.10/site-packages/sae_lens/training/training_sae.py", line 156, in encode
    feature_acts, _ = self.encode_with_hidden_pre(x)
  File "/home/ubuntu/git/IfYouDontUnderstandItDontUseIt/src/.venv/lib/python3.10/site-packages/sae_lens/training/training_sae.py", line 176, in encode_with_hidden_pre
    sae_in = self.hook_sae_input(x - (self.b_dec * self.cfg.apply_b_dec_to_input))
RuntimeError: The size of tensor a (64) must match the size of tensor b (1024) at non-singleton dimension 3
```

# Configuration
```json
{
    "model_name": "tiny-stories-1L-21M",
    "model_class_name": "HookedTransformer",
    "hook_name": "blocks.0.attn.hook_z",
    "hook_eval": "NOT_IN_USE",
    "hook_layer": 0,
    "hook_head_index": null,
    "dataset_path": "apollo-research/roneneldan-TinyStories-tokenizer-gpt2",
    "streaming": true,
    "is_dataset_tokenized": true,
    "context_size": 256,
    "use_cached_activations": false,
    "cached_activations_path": null,
    "d_in": 1024,
    "d_sae": 16384,
    "b_dec_init_method": "geometric_median",
    "expansion_factor": 16,
    "activation_fn": "relu",
    "normalize_sae_decoder": true,
    "noise_scale": 0.0,
    "from_pretrained_path": null,
    "apply_b_dec_to_input": true,
    "decoder_orthogonal_init": false,
    "decoder_heuristic_init": false,
    "init_encoder_as_decoder_transpose": false,
    "n_batches_in_buffer": 64,
    "training_tokens": 50000000,
    "finetuning_tokens": 0,
    "store_batch_size_prompts": 16,
    "train_batch_size_tokens": 128,
    "normalize_activations": false,
    "device": "cuda",
    "act_store_device": "cuda",
    "seed": 42,
    "dtype": "float32",
    "prepend_bos": true,
    "autocast": false,
    "autocast_lm": false,
    "compile_llm": false,
    "llm_compilation_mode": null,
    "compile_sae": false,
    "sae_compilation_mode": null,
    "adam_beta1": 0,
    "adam_beta2": 0.999,
    "mse_loss_normalization": null,
    "l1_coefficient": 0.001,
    "lp_norm": 1.0,
    "scale_sparsity_penalty_by_decoder_norm": false,
    "l1_warm_up_steps": 0,
    "lr": 0.0004,
    "lr_scheduler_name": "constant",
    "lr_warm_up_steps": 10000,
    "lr_end": 4e-05,
    "lr_decay_steps": 0,
    "n_restart_cycles": 1,
    "finetuning_method": null,
    "use_ghost_grads": false,
    "feature_sampling_window": 1000,
    "dead_feature_window": 1000,
    "dead_feature_threshold": 0.0001,
    "n_eval_batches": 10,
    "eval_batch_size_prompts": null,
    "log_to_wandb": true,
    "log_activations_store_to_wandb": false,
    "log_optimizer_state_to_wandb": false,
    "wandb_project": "sae_lens_tutorial",
    "wandb_id": null,
    "run_name": "16384-L1-0.001-LR-0.0004-Tokens-5.000e+07",
    "wandb_entity": null,
    "wandb_log_frequency": 10,
    "eval_every_n_wandb_logs": 100,
    "resume": false,
    "n_checkpoints": 0,
    "checkpoint_path": "my folder/my folder/my older/my folder/my folder/random string SAE lens appends apparently",
    "verbose": true,
    "model_kwargs": {},
    "model_from_pretrained_kwargs": {},
    "sae_lens_version": "3.0.0",
    "sae_lens_training_version": "3.0.0",
    "tokens_per_buffer": 2097152
}
```

# Code that Passes in Configuration
```python3
cfg = LanguageModelSAERunnerConfig(
                **config_copy,
            )
            import json # XXX
            print(json.dumps(cfg.__dict__, indent=4)) # XXX  <------ prints out what we said above
            # NOTE this is used implicitely in `language_model_sae_runner`
            layer_checkpoint_path = Path(cfg.checkpoint_path)
            layer_checkpoint_path.mkdir(
                parents=True, exist_ok=False
            ) 
            layer = cfg.hook_layer
            assert isinstance(layer, int)
            sae_training_runner = SAETrainingRunner(cfg)
            sparse_autoencoder: TrainingSAE = sae_training_runner.run() # <------ FAIL
```

# Solution (Not Acceptable)
Turn off wandb logging or comment out the some of the code in `site-packages`

**Comment by jbloomAus** [comment]
thanks @4gatepylon !
